#!/bin/bash
# Script para corrigir erro de build Docker com python-magic-bin

echo "🔧 Correções aplicadas para o build Docker:"
echo ""
echo "1. ✅ Removido python-magic-bin do requirements.txt"
echo "   - python-magic-bin é apenas para Windows"
echo "   - No Linux/Docker usamos libmagic nativo"
echo ""
echo "2. ✅ Atualizado Dockerfile para instalar dependências nativas:"
echo "   - libmagic1 e libmagic-dev (para python-magic)"
echo "   - poppler-utils (para pdf2image)"
echo ""
echo "3. 📦 Dependências adicionadas no builder stage:"
echo "   - libmagic-dev (para compilação)"
echo "   - poppler-utils (para processamento de PDF)"
echo ""
echo "4. 📦 Dependências adicionadas no runtime stage:"
echo "   - libmagic1 (para execução)"
echo "   - poppler-utils (para conversão PDF)"
echo ""
echo "✅ O build Docker agora deve funcionar corretamente!"
echo ""
echo "💡 Para testar localmente:"
echo "   docker build -t sdr-api ."
echo "   docker run -p 8000:8000 sdr-api"